### ISSUE TITLE
infinity_emb failed at startup using `torch.compile` when installed via pip

### ISSUE THREAD

**Issue by beebopkim** [michaelfeil/infinity#126]
commit hash: 296472eefaa93c361f086ea26bd7cd7e3c6e9a3e

I tried it on my Linux machne - Ubuntu 22.04 with CUDA 12.3, and it was failed.
```
% infinity_emb --device cuda --engine torch
2024-03-03 11:05:28.807 | WARNING  | fastembed.embedding:<module>:7 - DefaultEmbedding, FlagEmbedding, JinaEmbedding are deprecated. Use TextEmbedding instead.
INFO:     Started server process [4620]
INFO:     Waiting for application startup.
INFO     2024-03-03 11:05:29,079 infinity_emb INFO: model=`BAAI/bge-small-en-v1.5` selected, using engine=`torch` and device=`cuda`                               select_model.py:54
INFO     2024-03-03 11:05:29,378 sentence_transformers.SentenceTransformer INFO: Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5              SentenceTransformer.py:106
INFO     2024-03-03 11:05:31,576 infinity_emb INFO: Adding optimizations via Huggingface optimum. Disable by setting the env var `INFINITY_DISABLE_OPTIMUM`       acceleration.py:20
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
INFO     2024-03-03 11:05:31,580 infinity_emb INFO: Switching to half() precision (cuda: fp16). Disable by the setting the env var                        sentence_transformer.py:67
         `INFINITY_DISABLE_HALF`
INFO     2024-03-03 11:05:31,586 infinity_emb INFO: using torch.compile()                                                                                 sentence_transformer.py:73
zsh: segmentation fault (core dumped)  infinity_emb --device cuda --engine torch
%
```

I found issue #115 and ```export INFINITY_DISABLE_COMPILE=TRUE``` works. But it is strange that the default setting was failed. It is very strange.

**Comment by michaelfeil** [comment]
Interesting - torch.compile does not seem to work then. you might need gcc as a c++ installed. Best with e.g. build-essential?

Otherwise: Could you provide some longer logs - seems like they are not complete at the end.

**Comment by beebopkim** [comment]
Of course, gcc and g++ have been installed. Here are some version infos from my Linux machine:
```
% uname -a
Linux eleonora 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
% gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
%
```

And for log, I tried to run ```infinity_emb --device cuda --log-level debug``` to get more logs, but exactly same log was produced. % is the shell prompt because I am using zsh.

**Comment by michaelfeil** [comment]
Oh, I missed the segfault at the end of the script. 
What GPU is this on? 
Is the same happening via dockerfile (cuda12.1)?
Have you used other models with torch.compile?

**Comment by beebopkim** [comment]
My GPU is PNY 4060 Ti 16GB. And with the docker image, it run without any problem. Then II found that there was Python 3.10 in the docker image. So I tried with venv of 3.10, and it run well too. Strange, but the problem was solved. And for `pip install infinity-emb[all]` it did not work on both Python 3.10 and 3.11 in my case.

**Comment by michaelfeil** [comment]
Okay, if the docker image runs, I can provide no further assistance - its to hard to debug, I would guess some c++ extension might be incompatible.

Please install all the dependencies from the image on your system, or disable torch.compile

**Comment by michaelfeil** [comment]
Whats the advantage of your pip freeze - is this more helpful than poetry lock? https://github.com/michaelfeil/infinity/blob/main/libs/infinity_emb/poetry.lock

**Comment by beebopkim** [comment]
Because I'm very new to poetry?

**Comment by michaelfeil** [comment]
Closing for stale.
