### ISSUE TITLE
Multimodel inference

### ISSUE THREAD

**Issue by bacoco** [michaelfeil/infinity#13]
Will be great if we could load more models in the same container and switch between them using model name

**Comment by michaelfeil** [comment]
FYI, there is now a `mid-level` python API. You can build now your own FastAPI server, according to your needs.

**Comment by michaelfeil** [comment]
@bacoco Takeing suggestion for design patterns for this feature. If there is a good one, I might implement it #151

**Comment by michaelfeil** [comment]
I think launching this from command-line is basically not possible. 
It would be launching multiple models with `typer.cli` where most args are auto-generated.

Do you think a cli-setup from .yaml would be a good option? @bacoco

**Comment by michaelfeil** [comment]
Hey all, its fully implemented. @bacoco
