### ISSUE TITLE
"msg":"Input should be a valid list"

### ISSUE THREAD

**Issue by fishfree** [michaelfeil/infinity#130]
I totally adapted the OpenAI CURL example as below:
```
curl https://localhost:7997/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": "Your text string goes here",
    "model": "BAAI/bge-small-en-v1.5"
  }'
```

Infinity showed errors as below: `{"detail":[{"type":"list_type","loc":["body","input"],"msg":"Input should be a valid list"`.
I changed to:
```
curl https://localhost:7997/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": ["Your text string goes here"],
    "model": "BAAI/bge-small-en-v1.5"
  }'
```
It worked.

How can I modify Infinity codes to totally compatible with OpenAI API? Many thanks!

**Comment by michaelfeil** [comment]
Should be fixed with 0.0.26!

**Comment by michaelfeil** [comment]
https://github.com/michaelfeil/infinity/issues/98

https://github.com/michaelfeil/infinity/pull/99

**Comment by fishfree** [comment]
@michaelfeil Michael, would you please also update the docker image? For when run` pip install infinity-emb[all]`, the error still exists.

**Comment by michaelfeil** [comment]
The docker inage is released. Make sure to NOT pull "latest" but pin your image to a version, e.g. michaelf34/infinity:0.0.26 Thank you. 

https://github.com/michaelfeil/infinity/actions/runs/8118848897

**Comment by michaelfeil** [comment]
@fishfree Also, make sure that the version you have installed via pip is 0.0.26

**Comment by fishfree** [comment]
@michaelfeil Thank you, Michael!
