### ISSUE TITLE
Multi-Modal Inference / Clip

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#147]
Add support for MultiModal Inference / Clip

**Comment by tjtanaa** [comment]
How about adding API support to [JinaAi's clip-as-a-service](https://github.com/jina-ai/clip-as-service) or [Bentoml's clip-as-a-service](https://github.com/bentoml/CLIP-API-service/tree/main) ?
JinaAi's clip-as-a-service also supports running clip models on **onnx** and **tensorrt**.

**Comment by michaelfeil** [comment]
@tjtanaa Both have slightly outdated tech / few recent commits. 
I think https://github.com/jina-ai/clip-as-service got Jina started in the early days

**Comment by vlassisemm** [comment]
Hey, any progress here?

**Comment by michaelfeil** [comment]
@vlassisemm Actually hacking in Aleksa's Discord server live on it https://discord.gg/dtNDQhPJ (back at 3pm PST)

**Comment by michaelfeil** [comment]
#249 @vlassisemm
