### ISSUE TITLE
Update docs based on feeback.

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#148]
User feedback: I would suggest the following:

- [x] If you recommend running using a docker container, then lead with that and put the pip installation under a separate section.
- [x] ⁠I'd also add a common issues/Q&A to avoid getting a lot of repeated simple questions e.g. Why do I get: "docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]." error? A. You need to install nvidia-docker. Do "sudo apt install -y nvidia-docker2; sudo systemctl daemon-reload; sudo systemctl restart docker"
- [x] Add sample client code e.g. basic python request together with expected reply so this can be verified working e.g. you have sample code for running multiple models, maybe add a file which shows how to get an embedding from both models and the expected result.

**Comment by cduk** [comment]
Client code can be as simple as: curl -X POST -H 'Content-Type: application/json' -d '{"model": "bge-small-en-v1.5", "input":"A very large brown cat ate the pigeon."}' http://embeddinghost:7997/embeddings

**Comment by michaelfeil** [comment]
@cduk Would it make sense to generate an example with OpenAI client an openapi client?
