### ISSUE TITLE
Dynamic loading - different models at request time / multiple models

### ISSUE THREAD

**Issue by cduk** [michaelfeil/infinity#151]
Instead of running an instance per model in the dockerfile. Can a list of models be provided at instantiation and then the model is chosen via the api request. The current API already has model as a parameter.

**Comment by michaelfeil** [comment]
Interesting idea:
- What parameters would you launch the model with (always the same?)
- Would you prefer to launch multiple models at a time?
- How long would you keep a model "active" before "unloading it"?

**Comment by cduk** [comment]
The simpler way would be not do deal with loading and unloading and require all models fit in VRAM and then you select which one you use in the API call.

**Comment by michaelfeil** [comment]
So basically add multiple models in the cli at startup?

**Comment by cduk** [comment]
Exactly!

**Comment by michaelfeil** [comment]
This is completed. see #13
