### ISSUE TITLE
Missing library for nomic-ai/nomic-embed-text-v1.5 model

### ISSUE THREAD

**Issue by shubham-bnxt** [michaelfeil/infinity#197]
### Model description

For deploying embedding mode nomic-ai/nomic-embed-text-v1.5 additional dependency for einops is required in docker image

### Open source status

- [X] The model implementation is available on transformers
- [X] The model weights are available on huggingface-hub
- [X] I verified that the model is currently not running in infinity

**Comment by michaelfeil** [comment]
#185 duplicate.

**Comment by michaelfeil** [comment]
https://huggingface.co/nomic-ai/nomic-embed-text-v1.5/discussions/16#6616ca28401ac37f878f4701
