### ISSUE TITLE
 API Key Authentication for Michaelfeil Infinity

### ISSUE THREAD

**Issue by AjayKarma05** [michaelfeil/infinity#207]
### Model description

Could you please provide guidance on how to enable API_KEY authentication? Alternatively, is there a plan to implement API_KEY authentication similar to OpenAI's approach?

### Open source status

- [ ] The model implementation is available on transformers
- [ ] The model weights are available on huggingface-hub
- [ ] I verified that the model is currently not running in infinity

**Comment by semoal** [comment]
It's just a fastapi server, implement it as usual like you do on FastAPI.

**Comment by michaelfeil** [comment]
I added an example on how to use infinity with runpod.io

note, that API_Keys are typically not set, they are generated. Also they are not verified by the application itself, but by e.g. AWS API Gateway. I understand ypur interest, but i think such a feature is easy to implement yourself or better be added with another service

**Comment by michaelfeil** [comment]
https://github.com/monotykamary/infinity/commit/36680ae5435eac2e7db2ec70963ee82121943f10

@monotykamary has implemented it. Changed my mind: If the contribution is easy enough, comes with a unit test that covers every LOC, and defaults to no api key as default behauviour, would be accepted

**Comment by monotykamary** [comment]
Oh, I just did a dirty implementation to quickly spin up a quick embedding server with auth on Modal: https://github.com/dwarvesf/llm-hosting/blob/main/infinity_snowflake_arctic_embed_l_335m.py

**Comment by michaelfeil** [comment]
Looks not dirty at all @monotykamary! Awesome

**Comment by michaelfeil** [comment]
@monotykamary @semoal Added API auth

**Comment by Jimmy-Newtron** [comment]
How to set the API_KEY in the Langchain Infinity Embedding?

**Comment by michaelfeil** [comment]
@Jimmy-Newtron PRs to langchain are welcome.
