### ISSUE TITLE
Support for Python 3.8 in infinity

### ISSUE THREAD

**Issue by BarryRun** [michaelfeil/infinity#209]
### Feature request

I am currently working on a project that has strict environmental requirements and dependencies which necessitate the use of Python 3.8. However, I have encountered issues when trying to use the infinity package in this Python version. Both installation methods via pip and building from source have been unsuccessful.

### Motivation

The inability to install infinity on Python 3.8 is posing a significant impediment to the progress of our project. Given that Python 3.8 is still widely used and that other project dependencies are not compatible with newer Python versions, it is crucial for our project to have infinity package support for Python 3.8.

### Your contribution

None

**Comment by michaelfeil** [comment]
Hey, I made some efforts when merging rhe AWS inferentia packages. As this packages relies on e.g. strong type checking.

Python 3.8 reaches end-of-life in 5 months as of this comments date (10/24). I have not seen any compelling reasons for downgrading to 3.8, the minimum is 3.9. 

If your project has a high relevancy, Id be happy to work on a 3.8 compatible version as special release. Feel free to reach out via email for me for that.
