### ISSUE TITLE
Loading models from local path

### ISSUE THREAD

**Issue by vladimirmujagic** [michaelfeil/infinity#217]
### Feature request

Is it really not possible to load models from path instead of huggingface repo?

### Motivation

Allows the server to run in environments where downloading from hugging face is not possible

### Your contribution

I can help if needed, yes.

**Comment by michaelfeil** [comment]
@vladimirmujagic Thanks for opening. This is possible, however, there are a lot of files besides the `model.safetensors`. Only thing I can recommend is to prime your cache, e.g. patching in your model. Does #204 #205 help?

**Comment by michaelfeil** [comment]
Closeing because of duplicate #205 Comment there.
