### ISSUE TITLE
Docker path not in readme

### ISSUE THREAD

**Issue by hughesadam87** [michaelfeil/infinity#222]
Real quick - from the docs it wasn't clear how to pull a prebuilt docker image. For example, is it this one?

     [docker pull cledge/infinity](https://hub.docker.com/r/cledge/infinity)

**Comment by michaelfeil** [comment]
It is in the readme. Michaelf34/infinity. 

https://github.com/michaelfeil/infinity?tab=readme-ov-file#launch-the-cli-using-a-pre-built-docker-container-recommended

**Comment by hughesadam87** [comment]
Ok - when I searched "infinity" on dockerhub I didn't see, so I would recommend putting the full dockerhub URL clearly in the readme, just my 2c.    IE

     docker pull https://hub.docker.com/u/michaelf34

**Comment by michaelfeil** [comment]
Just updated the readme - is it more visible now?
