### ISSUE TITLE
Include `einops` in docker image

### ISSUE THREAD

**Issue by chiragjn** [michaelfeil/infinity#231]
### Feature request

As the title states, add einops as dependency either for infinity_emb package or in the Dockerfile

### Motivation

Few models rely on `einops` for their modeling code. It would be nice to be able to run these models directly without having to build custom docker image.
example: https://huggingface.co/Snowflake/snowflake-arctic-embed-m-long/blob/08e7a4449e3f07709fb9387bc3172d393a6cc5e2/modeling_hf_nomic_bert.py#L18

I realise that models on HF Hub are free to use arbitrary dependencies but `einops` seems common enough to include for convenience

### Your contribution

Happy to open a PR based on decision

**Comment by michaelfeil** [comment]
But if you open a new group with `einops = "*"` as optional package, that is part of the default group (installed via `pip install infinity_emb[all]` and `infinity_emb[einops]` that would be OKAY. @chiragjn Are you up for such a PR?
