### ISSUE TITLE
Embedding quantization

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#245]
### Feature request

Quantization against:
- https://huggingface.co/blog/embedding-quantization

### Motivation

-

### Your contribution

Looking for contributors to fill the blank of embedding quanitzation. 

```python

@cache 
def quantize_embedding_stats(model: str, dataset: some_dataset.parquet) -> statistics[min,max,median,other]:
      ...
      
def quanize_embeddings()
     quantize_embedding_stats()
```

**Comment by mahiro72** [comment]
Hello @michaelfeil , I'm interested in working on this issue. Can I give it a try?

**Comment by michaelfeil** [comment]
Actually started to implement a rough sketch! But then i continued working on it, and it might have solced it entirely. Want to give it a try? @mahiro72

**Comment by michaelfeil** [comment]
#247

**Comment by michaelfeil** [comment]
@mahiro72 moved it to here: https://github.com/michaelfeil/infinity/issues/250

**Comment by mahiro72** [comment]
@michaelfeil 
Thank you! I would like to work on this issue to verify the performance.
https://github.com/michaelfeil/infinity/issues/250
