### ISSUE TITLE
[CLIP][Server/Engine] Send images to engine / accept PIL images

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#258]
### Feature request

Instead of sending the URL

Breakdown:
- Allow engine to accept images. Aka: Engine.embed_image(images: list[url | Image]) -> list[Embeddings]. Currently only supports url strings
-  Allow API to download images

### Motivation

Currently you can send only URLS. Goal would be to have a efficent and maintainable (add a test) solution

### Your contribution

Looking for contributors!

**Comment by lckr** [comment]
This feature request was implemented in #353, closing this issue.
