### ISSUE TITLE
Adding kwargs for inference

### ISSUE THREAD

**Issue by hyeinkoo** [michaelfeil/infinity#262]
### Feature request

Enable passing additional model arguments when sending a request. kwargs like `{'normalize_embeddings': False}`.

### Motivation

Currently, the output is normalized by default, but I would like to obtain unnormalized embeddings as well. 

### Your contribution

Anything if i can

**Comment by michaelfeil** [comment]
This most likely cannot be done. I am sorry. Reasons:

- Torch normalizes all https://huggingface.co/BAAI/bge-small-en-v1.5/blob/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json#L18
- To much business logic: Infinity additonally normalizes all vectors as a batch.
- No value for non-normalized vectors other than slight performance improvements if you skip this computation. 
- Unnormalized vectors are a big source of errors with database engineers
