### ISSUE TITLE
When I installed infinity using poetry, it was easy to conflict with the torch versions of other frameworks because the torch version was too high.

### ISSUE THREAD

**Issue by shell-nlp** [michaelfeil/infinity#263]
### Feature request

When I installed infinity using poetry, it was easy to conflict with the torch versions of other frameworks because the torch version was too high.

### Motivation

When I installed infinity using poetry, it was easy to conflict with the torch versions of other frameworks because the torch version was too high.

### Your contribution

When I installed infinity using poetry, it was easy to conflict with the torch versions of other frameworks because the torch version was too high.

**Comment by michaelfeil** [comment]
Hey @shell-nlp,

Whats the range of torch versions you are looking for?

2.2+ is required to enable torch.compile with dynamic shapes + torch.nested_tensor and 2.3 for e.g. fp8 / quant. 
there might be a lot of things breaking, and I dont want to maintain / be responsible for those!

Can you help me to see which packages you mean so I can evaluate what is possible.

**Comment by shell-nlp** [comment]
![image](https://github.com/michaelfeil/infinity/assets/39985245/3205a386-2c51-462e-acdf-4dc18f3a1742)
The prometheus-fastapi-instrumentator version needs to be upgraded to >=7.0

**Comment by michaelfeil** [comment]
Ah, so its not related on torch. Working on it tonight.

**Comment by michaelfeil** [comment]
Should be done with 0.0.43
