### ISSUE TITLE
The request to the /v1/embeddings endpoint returned a 404 status code.

### ISSUE THREAD

**Issue by monkdharma** [michaelfeil/infinity#298]
### Model description

When I loaded the embedding model and tested the request, it returned a 404 status code. Is this because Infinity does not support requests in the form of /v1/embeddings?

```
curl http://127.0.0.1:8000/v1/embeddings \
    -X POST \
    -H 'Content-Type: application/json' \
   -d '{
  "model": "bge-large-zh-v1.5",
  "embedding_format": "float",
  "input": "What is Deep Learning"
  }'
  ```

### Open source status

- [ ] The model implementation is available on transformers
- [ ] The model weights are available on huggingface-hub
- [ ] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

**Comment by michaelfeil** [comment]
@monkdharma Please use the url-prefix feature for `v2 --url-prefix "v1"

**Comment by wirthual** [comment]
Just verified setting `v2 --url-prefix /v1` works as intended.  

Used command to start server:
```
infinity_emb v2 --url-prefix /v1 --port 8000
```

Result from curl command from above:
```
curl http://127.0.0.1:8000/v1/embeddings     -X POST     -H 'Content-Type: application/json'    -d '{
  "model": "bge-large-zh-v1.5",
  "embedding_format": "float",
  "input": "What is Deep Learning"
  }'
{"object":"embedding","data":[{"object":"embedding","embedding":[-0.005...
```
