### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

### ISSUE THREAD

**Issue by gokturkDev** [michaelfeil/infinity#304]
### System Info

Not about system

### Information

- [X] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`docker run -it --gpus all -v $PWD/data:/app/.cache -p 80:80 michaelf34/infinity:latest v2 --model-id dunzhang/stella_en_1.5B_v5 --port 80 `

This happens in Alibaba-NLP/gte-Qwen2-7B-instruct model as well.

### Expected behavior

I believe this has resurfaced in #17  #125 in the past

So, is flash_attn not supported in infinity or is this a bug? If it's not supported, am I out of luck for running these models? My usecase strongly depends on the latest, most powerful embedding models. Stella and Qwen are in top 5 for MTEB, so its a real pity I cannot run them. Is there any chance support for it would be integrated into infinity? What are the roadblocks for it?

**Comment by michaelfeil** [comment]
Hi @gokturkDev - not willing to add flash-attn to the docker. Please raise an issue at alibaba (their model repo) / huggingface transformers that you want `torch.scaled_dot_product_attention` support. Flash-attn impacts support e.g. on cpu's, amd.

**Comment by michaelfeil** [comment]
Well flash-attn has pre-build wheels -> You can try to install them from souce. Can't give you advice 
flash_attn-2.6.1+cu118torch2.0cxx11abiFALSE-cp311-cp311-linux_x86_64.whl https://github.com/Dao-AILab/flash-attention/releases/tag/v2.6.1

**Comment by gokturkDev** [comment]
For future reference if anybody ever tries this,

1. flash-attn doesn't support poetry build
https://github.com/Dao-AILab/flash-attention/issues/927#issue-2259831815

The only solution I found was to download the wheels from the releases in the github repo and install the wheels. Which brings me to

2. flash-attn has no support for Cuda 12.*

As seen here 
https://github.com/Dao-AILab/flash-attention/issues/728

The only way to get this working is to use Cuda 11.8

3.  Which results in 
ImportError: /app/.venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by gokturkDev** [comment]
> Well flash-attn has pre-build wheels -> You can try to install them from souce. Can't give you advice but e.g. `flash_attn-2.6.1+cu118torch2.0cxx11abiFALSE-cp311-cp311-linux_x86_64.whl` is version 2.6.1 for cuda-torch 11.8 and torch 2.0.x when python is 3.11. That should resolve installation. Because of buffers, some gpus cannot work (depends on their cache sizes and head dim of the model you are using.) https://github.com/Dao-AILab/flash-attention/releases/tag/v2.6.1

Hi thanks for the response, I havent tried with torch 2.0.x since infinity uses torch >=2.20, correct?

**Comment by gokturkDev** [comment]
`flash_attn-2.6.1+cu118torch2.4cxx11abiTRUE-cp311-cp311-linux_x86_64.whl is not a supported wheel on this platform.`
I have tried torch 2.3 and 2.4 but I get the error above

**Comment by gokturkDev** [comment]
`flash_attn-2.6.1+cu118torch2.0.cxx11abiFALSE-cp311-cp311-linux_x86_64.whl is not a supported wheel on this platform.`

Same error with the wheel you shared unfortunately

**Comment by gokturkDev** [comment]
I am sick with flash_attention so I am going to try running other models with similar performance. Thanks for your help @michaelfeil 

Clues for future:
Flash attention repo appears to not be maintained pretty well, so the solution probably lies in downgrading both torch and flash attention and using the image mentioned below. 
https://github.com/Dao-AILab/flash-attention/issues/631#issuecomment-1820931085
https://github.com/Dao-AILab/flash-attention/issues/208#issuecomment-1546333020

**Comment by michaelfeil** [comment]
Well, you need also to select the right platform (linux) and right version. Anyways!

**Comment by gokturkDev** [comment]
I am running this on a fresh ec2 amazon linux instance with cuda support.

**Comment by michaelfeil** [comment]
@gokturkDev

I created a special release with FA2 wheels installed in the docker file. Does this work?

```
docker run -it michaelf34/infinity:0.0.52-fa  v2 --port 8000 --model-id Alibaba-NLP/gte-Qwen2-1.5B-instruct 
```

**Comment by DrChiZhang** [comment]
> For future reference if anybody ever tries this,
> 
>     1. flash-attn doesn't support poetry build
>        [flash-attn (2.3.0) not supporting PEP 517 builds Dao-AILab/flash-attention#927 (comment)](https://github.com/Dao-AILab/flash-attention/issues/927#issue-2259831815)
> 
> 
> The only solution I found was to download the wheels from the releases in the github repo and install the wheels. Which brings me to
> 
>     2. flash-attn has no support for Cuda 12.*
> 
> 
> As seen here [Dao-AILab/flash-attention#728](https://github.com/Dao-AILab/flash-attention/issues/728)
> 
> The only way to get this working is to use Cuda 11.8
> 
>     3. Which results in
>        ImportError: /app/.venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I have the same issue, and I have update cuda to 12.1, while have the issue of 
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

Did you find the solution?

**Comment by gokturkDev** [comment]
> > For future reference if anybody ever tries this,
> 
> > 
> 
> >     1. flash-attn doesn't support poetry build
> 
> >        [flash-attn (2.3.0) not supporting PEP 517 builds Dao-AILab/flash-attention#927 (comment)](https://github.com/Dao-AILab/flash-attention/issues/927#issue-2259831815)
> 
> > 
> 
> > 
> 
> > The only solution I found was to download the wheels from the releases in the github repo and install the wheels. Which brings me to
> 
> > 
> 
> >     2. flash-attn has no support for Cuda 12.*
> 
> > 
> 
> > 
> 
> > As seen here [Dao-AILab/flash-attention#728](https://github.com/Dao-AILab/flash-attention/issues/728)
> 
> > 
> 
> > The only way to get this working is to use Cuda 11.8
> 
> > 
> 
> >     3. Which results in
> 
> >        ImportError: /app/.venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> 
> 
> 
> I have the same issue, and I have update cuda to 12.1, while have the issue of 
> 
>     import flash_attn_2_cuda as flash_attn_cuda
> 
> ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
> 
> 
> 
> Did you find the solution?

Check out https://github.com/michaelfeil/infinity/pull/313
