### ISSUE TITLE
403 Forbidden error on input size bigger than 2048

### ISSUE THREAD

**Issue by gokturkDev** [michaelfeil/infinity#307]
### Feature request

Currently, the maximum size for the input array for the embeddings endpoint is set to 2048
Inspecting `libs\infinity_emb\infinity_emb\fastapi_schemas\pymodels.py` verifies this

``` # Note: adding artificial limit, this might reveal splitting
        # issues on the client side
        #      and is not a hard limit on the server side.
        INPUT_STRING = StringConstraints(max_length=8192 * 15, strip_whitespace=True)
        ITEMS_LIMIT = {
            "min_length": 1,
            "max_length": 2048,
        }
    except ImportError:
        from pydantic import constr

        INPUT_STRING = constr(max_length=8192 * 15, strip_whitespace=True)  # type: ignore
        ITEMS_LIMIT = {
            "min_items": 1,
            "max_items": 2048,
        }
        HttpUrl, AnyUrl = str, str  # type: ignore
```
        
If this is an artifical limit, can we add an environment variable to instead of hardcoding this to 2048?

### Motivation

I am using this for a RAG pipeline, so it would be nice if I could send all of my chunks at once

### Your contribution

Point me to how cli arguments are parsed and I can send a PR

**Comment by michaelfeil** [comment]
I am using this for a RAG pipeline, so it would be nice if I could send all of my chunks at once -> You potentially want to chunk them into blocks of 128 with a max parallel. 

Background: Node-Balancing, HTTP-Timeouts.

**Comment by gokturkDev** [comment]
Hey sorry about this, this isn't related to infinity at all. It was due to sending more data than allowed in the http protocol.
