### ISSUE TITLE
FacebookAI/roberta-large-mnli uses CPU instead of GPU

### ISSUE THREAD

**Issue by yaronr** [michaelfeil/infinity#319]
### System Info

michaelf34/infinity:0.0.52-fa
Single L4 GPU, 64GB memory RAM.

### Information

- [X] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

'''
INFO     2024-07-22 13:23:25,707 infinity_emb INFO:           select_model.py:57
         model=`FacebookAI/roberta-large-mnli` selected,                        
         using engine=`torch` and device=`None`                                 
Some weights of the model checkpoint at FacebookAI/roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
'''

### Expected behavior

I expect it to use the GPU if it's available.

**Comment by michaelfeil** [comment]
What is the actual error - I think there is no issue here. The output is just verbose.

The paragraph below means:
model=FacebookAI/roberta-large-mnli selected,
using engine=torch and device=None
Some weights of the model checkpoint at FacebookAI/roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']

you loaded the model to do classification, but we still have our embedding head besides of the classification head. As classification is not using these weights, it’s weird to the base class to see them included.
As a result this warning occurns.
