### ISSUE TITLE
Does InfinityEmbeddings server work with OpenAIEmbeddings properly?

### ISSUE THREAD

**Issue by vmarchenkoff** [michaelfeil/infinity#329]
### System Info

michaelf34/infinity:latest

### Information

- [X] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`bash
docker run -it --gpus all -v ~/llms/:/app/.cache -p 8000:8000 michaelf34/infinity:latest v2 --model-id ~/llms/multilingual-e5-large --port 8000
`

```python3
from openai import OpenAI

openai_api_key = "DUMMY"
openai_api_base = "http://<BASE_URL>:8000"
client_emb = OpenAI(api_key=openai_api_key, base_url=openai_api_base)

models = client_emb.models.list()
model = models.data[0].id

responses = client_emb.embeddings.create(input=['phrase1', 'phrase2'], 
                                         model=model)
for data in responses.data:
    print(data.embedding[:5])
```

works just fine.

```python3
from langchain_community.embeddings import InfinityEmbeddings

infinity_api_url = "http://<BASE_URL>:8000"

embeddings = InfinityEmbeddings(
    model=model, infinity_api_url=infinity_api_url
)

query = "phrase1"

documents = ["phrase1", "phrase2"]

try:
    query_result = embeddings.embed_query(query)
    docs_result = embeddings.embed_documents(documents)
    print("embeddings created successful")
except Exception as ex:
    print(
        "Make sure the infinity instance is running. Verify by clicking on "
        f"{infinity_api_url.replace('v1','docs')} Exception: {ex}. "
    )

print(len(docs_result))
print(len(query_result))
print(query_result[:5])
```

works fine as well, but:

```python3
from langchain_openai import OpenAIEmbeddings

openai_api_key = "DUMMY"
openai_api_base = "http://<BASE_URL>:8000"

client_emb = OpenAIEmbeddings(api_key=openai_api_key,  base_url=openai_api_base)

client_emb.embed_query('Hello world')
```

fails with Time Out error. What did i miss here? The reason that i would like to use OpenAIEmbeddings instead of InfinityEmbeddings is possibility to use api-key which is not incorporated to langchain's InfinityEmbeddings.

Thank you in advance and thank you for this beautiful project!

### Expected behavior

The same as for OpenAI client and InfinityEmbeddings.

**Comment by michaelfeil** [comment]
Search for related issues here before opening.

 langchain pretokenizes the text with the tiktoken tokenizer

**Comment by vmarchenkoff** [comment]
As I understood, there is no way to use OpenAIEmbeddings with Infinity instance because of model's specific tokenization , InfinityEmbeddings was implemented to solve this (https://github.com/michaelfeil/infinity/issues/36). 
But the api-key feature is not implemented yet in langchain's InfinityEmbeddings.

Sorry for inconvenience, i saw the issue above before opening this one, but translated it to another problem.

Thank you for you answer and for your work in general, this is the beautiful project, very important and useful.

**Comment by michaelfeil** [comment]
@vmarchenkoff Makes sense! ` But the api-key feature is not implemented yet in langchain's InfinityEmbeddings.` - Correct. 
I would recommend using https://github.com/michaelfeil/infinity/tree/main/libs/client_infinity/infinity_client / `pip install infinity_client` for usage.

**Comment by vmarchenkoff** [comment]
Thank you! 

It looks much more customisable and serious, guess I have to use default clients for vector DB and Embeddings in my RAG project instead of third-party integrations.
