### ISSUE TITLE
BAAI/bge-reranker-v2-gemma

### ISSUE THREAD

**Issue by Jimmy-Newtron** [michaelfeil/infinity#333]
### Model description

The model is loaded but strangely it has capabilities of embedding and no rerank

````
{
      "id": "BAAI/bge-reranker-v2-gemma",
      "stats": {
        "queue_fraction": 0,
        "queue_absolute": 0,
        "results_pending": 0,
        "batch_size": 32
      },
      "object": "model",
      "owned_by": "infinity",
      "created": 1723476182,
      "backend": "torch",
      "capabilities": [
        "embed"
      ]
    }
````

### Open source status

- [X] The model implementation is available on transformers
- [X] The model weights are available on huggingface-hub
- [ ] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

**Comment by michaelfeil** [comment]
Gemma is a Causal LM, that has no reranking / classification head. This is not supported. FlagLLMReranker
