### ISSUE TITLE
Mismatch between sentence transformer embeddings and infinite embed v2

### ISSUE THREAD

**Issue by nitinrawatiitd** [michaelfeil/infinity#336]
### System Info

OS version: Linux
Model used: sentence-transformers/all-MiniLM-L6-v2
Hardware: 2xV100

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Hi,

I see a difference between the embeddings generated using sentence transformers, in python, like this:
```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode("2024")
print(f"{embeddings[-1]:.20f}")
```

and the embeddings generated from the infinity embed v2 API.
1. CLI command to serve the embedding model:
```bash
infinity_emb v2 --port 7780 --device cuda --model-id sentence-transformers/all-MiniLM-L6-v2 --dtype float32
```
2. cURL command to get the embeddings for the text "2024"
```bash
curl --request POST --url http://127.0.0.1:7780/embeddings --header "Content-Type: application/json" --data '{"model":"sentence-transformers/all-MiniLM-L6-v2","input": "2024"}'
```

There is a difference, a minute difference but a difference still, between the embeddings generated by the 2 methods. I thought quantization was the culprit. It was, but the values still don't match. For example:

- From the first approach, the last value in the embedding generated is -0.00783606525510549545
- From the API approach, the last value in the embedding generated is -0.007809564936906099

Does anyone know the reason for this difference?

### Expected behavior

Infinity embed v2 should ideally give the same embeddings as those generated from sentence-transformers, for the same embedding model, for the same word

**Comment by michaelfeil** [comment]
The difference is a fast version of flash attention that infinity uses. 

This will have 0 downstream performance issues, closing.

**Comment by nitinrawatiitd** [comment]
Thank you @michaelfeil
