### ISSUE TITLE
BGE-m3 (dense + sparse) support

### ISSUE THREAD

**Issue by Hokyjack** [michaelfeil/infinity#340]
Hello, i am using BGE-m3 model, which should support generating Dense + Sparse vector in a single call.
Is there any option, to get both vectors (dense + sparse) when using Infinity /embedding request?
Right now I only see the output of dense array.
Reference: https://huggingface.co/BAAI/bge-m3

**Comment by michaelfeil** [comment]
#146 Duplicate

**Comment by Hokyjack** [comment]
thanks, i just don't understand in the Infinity code, where the actual calling of the model happens ("forward"), and where is the parsing of the output? Can you give me some hints?
