### ISSUE TITLE
Embedding High VRAM Usage

### ISSUE THREAD

**Issue by etwk** [michaelfeil/infinity#341]
After starting the model `jinaai/jina-embeddings-v2-base-en`, Infinity uses 5424MiB VRAM, while Ollama uses 1030MiB.

Is this normal, and any way to reduce Infinity VRAM usage here?

BTW, I like this project very much, thanks!

**Comment by michaelfeil** [comment]
What batch size is ollama running in parallel at maximum?
 Try reduce the —batch-size to 1!

**Comment by etwk** [comment]
> What batch size is ollama running in parallel at maximum? Try reduce the ‘—batch-size to 1’ in the cli and see how they compare.

I believe ollama does not support batch yet.

Infinity with ` --batch-size 1` uses about the same VRAM, 5428MiB.

**Comment by michaelfeil** [comment]
Maybe compare some other models, I suspect that it's mainly due sequence length.

I invite you to try the code-base-v2 model, `infinity_emb v2 --model-id michaelfeil/jina-embeddings-v2-base-code` with patched sequence length. Locally, this uses `1568MiB`, down from `5400MiB`. The VRAM is roughly base model `~800Mib + 0.4*sequence_length_in_tokens`. 

Both, Ollama and infinity would go out of memory, if you send a large batch of `(32,8192) or (1,8192)` through it.
