### ISSUE TITLE
add support for deberta

### ISSUE THREAD

**Issue by Stealthwriter** [michaelfeil/infinity#344]
### Feature request

deberta is the best text classification model, can you add it?

### Motivation

deberta is the best text classification model, can you add it?

### Your contribution

deberta is the best text classification model, can you add it?

**Comment by michaelfeil** [comment]
its currently supported, or whats the issue?

**Comment by michaelfeil** [comment]
Closing, as question is unclear and Deberta is supported. The Reranker in infinity pulls even the Deberta Model as main example. https://huggingface.co/mixedbread-ai/mxbai-rerank-xsmall-v1/tree/main is covered in multiple unit tests. Therefore closing.
