### ISSUE TITLE
embeddings_image not work with model-id sentence-transformers/clip-ViT-B-32-multilingual-v1

### ISSUE THREAD

**Issue by xyxu** [michaelfeil/infinity#345]
### System Info

infinity_emb  0.0.54

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. infinity_emb v2 --model-id sentence-transformers/clip-ViT-B-32-multilingual-v1
2. curl -v -H 'content-type:application/json' -d '{"model":"sentence-transformers/clip-ViT-B-32-multilingual-v1","input":["http://images.cocodataset.org/val2017/000000039769.jpg"]}' http://0.0.0.0:7997/embeddings_image
3. {"error":{"message":"ModelNotDeployedError: model=`sentence-transformers/clip-ViT-B-32-multilingual-v1` does not support `embed`. Reason: the loaded moded cannot fullyfill `image_embed`.options are {'embed'}.","type":null,"param":null,"code":400}}

### Expected behavior

return image embedding

**Comment by michaelfeil** [comment]
@xyxu Seems like this model is using architectures": [
    "DistilBertModel"
  ]
And not clip!

**Comment by xyxu** [comment]
> @xyxu Seems like this model is using architectures": [ "DistilBertModel" ] And not clip!

Solved, thank you
