### ISSUE TITLE
Support `encoding_format` from the official OpenAI-API for compatibility

### ISSUE THREAD

**Issue by Matti-Koopa** [michaelfeil/infinity#349]
### Feature request

This API doesn't support `encoding_format`.
This makes it so that Infinity doesn't work on certain OpenAI-API-libraries such as the official one for C#. See here: https://github.com/openai/openai-dotnet/issues/51
Please add this parameter.

### Motivation

Compatibility

**Comment by michaelfeil** [comment]
@Matti-Koopa Thanks for raising the issue! Reading https://platform.openai.com/docs/api-reference/embeddings/create this can be either float or base64.

1. Do you have a closer description on which level they are base64 encoded? I assume, its the 1D array?
2. Do you want base64 feature, or just an adaption to accept an optional parameter “encoding=float”?

**Comment by Matti-Koopa** [comment]
[This ](https://community.openai.com/t/help-decoding-base64-embeddings-in-nodejs/599308/2)says it's a buffer of float.
Probably easily tested using the OpenAI API.

The official OpenAI C# library (and probably also their other supported languages libraries) currently hard-codes (!) sending `"encoding_format": "base64"` in each embedding request and only support deserialization of base64 strings for the embeddings response. They asy it's for performance reasons.
Thus I think the only possible way to make those libraries work with Infinity would be to properly implement both the base64 input parameter and output format.

**Comment by guillaumerenault** [comment]
I am also looking for such as feature (the "base64 feature", not an adapation to use your own words @michaelfeil), currently supplying `base64` as value to `encoding_format` returns floats which can be misleading for users / SDKs who expect OpenAI compatibility.

**Comment by michaelfeil** [comment]
Interesting, the buffer is somewhat ambiguous. 

Got an inital code working, 
```
embeddings = [base64.b64encode(np.frombuffer(emb.astype(np.float32), dtype=np.float32)) for emb in embeddings]
```

According to https://community.openai.com/t/help-decoding-base64-embeddings-in-nodejs/599308/4 this is the client code.
```
embedding_base64 = np.frombuffer(
        base64.b64decode(embedding_base64), dtype=np.float32
    ).tolist()
```

I'll tag you in the PR if I need further help or testing of the PR.

**Comment by michaelfeil** [comment]
@Matti-Koopa @guillaumerenault Can you test if the following dockerfile `docker.io/michaelf34/infinity:0.0.54-feature-base64` works for you? If it works, I'll merge the PR.

**Comment by Matti-Koopa** [comment]
Testet the image and - yes it works @michaelfeil 
Thank you.

**Comment by guillaumerenault** [comment]
Image works for me as well. My tests were successful (I am using https://github.com/sashabaranov/go-openai).
Thank you!

**Comment by michaelfeil** [comment]
Awesome, thank you both for checking it out!
