### ISSUE TITLE
minicpm3-embedding and minicpm3-reranker

### ISSUE THREAD

**Issue by lyj157175** [michaelfeil/infinity#354]
### Model description

minicpm3's embedding and reranker models can support?

### Open source status

- [ ] The model implementation is available on transformers
- [X] The model weights are available on huggingface-hub
- [ ] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

**Comment by michaelfeil** [comment]
@lyj157175 Which models (huggingface link) are you talking about?

**Comment by michaelfeil** [comment]
I think https://huggingface.co/openbmb/MiniCPM-V-2 is a text-generation model (chat). For multi-model chat, I would recommend using https://github.com/vllm-project/vllm . This repo is for multi-model embeddings and reranking.

**Comment by lyj157175** [comment]
https://huggingface.co/openbmb/MiniCPM-Embedding

**Comment by lyj157175** [comment]
I mean these two models. These two are embedding and reranker models. Can vllm only load the chat model?
https://huggingface.co/openbmb/MiniCPM-Embedding
https://huggingface.co/openbmb/MiniCPM-Reranker

**Comment by michaelfeil** [comment]
Yes, via `pip install infinity_emb[all] flash-attn`
