### ISSUE TITLE
prepend v1 to OpenAI compatible APIs

### ISSUE THREAD

**Issue by samos123** [michaelfeil/infinity#371]
### Feature request

prepend v1 to OpenAI compatible APIs

### Motivation

This allows us to integrate infinity the same way as other openai compatible API engines into KubeAI: https://github.com/substratusai/kubeai

PR: https://github.com/substratusai/kubeai/pull/197

### Your contribution

Yeah I could probably do it once I get go ahead from you.

**Comment by samos123** [comment]
Seems the response isn't exactly following the OpenAI response. This is from OpenAI docs:
![image](https://github.com/user-attachments/assets/607def22-7262-4411-b079-7fc2ed12ad69)

And this is what Infinity returns: 
```
{
  "object": "embedding",
  "data": [
    {
      "object": "embedding",
      "embedding": [
```

The "object" should be "list" but infinity returns "embedding". Not sure if this matters though but sharing observation here.

**Comment by samos123** [comment]
I confirmed that this is blocking integration with KubeAI:
```
INFO:     10.244.0.15:35798 - "POST /v1/embeddings HTTP/1.1" 404 Not Found
INFO:     10.244.0.15:35798 - "POST /v1/embeddings HTTP/1.1" 404 Not Found
INFO:     10.244.0.1:43268 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.15:35798 - "GET /metrics HTTP/1.1" 200 OK
INFO:     10.244.0.1:50798 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.1:50796 - "GET /health HTTP/1.1" 200 OK
INFO:     10.244.0.15:40274 - "GET /metrics HTTP/1.1" 200 OK
INFO:     10.244.0.15:40274 - "POST /v1/embeddings HTTP/1.1" 404 Not Found
```

**Comment by samos123** [comment]
I may be able to make this work with `url_prefix`. Giving that a try.

**Comment by benoitdion** [comment]
>The "object" should be "list" but infinity returns "embedding". Not sure if this matters though but sharing observation here

@samos123 this is indeed an issue. Using an openai compatible clients errors out since the response json is incompatible.

**Comment by wirthual** [comment]
Hi @benoitdion ,
Thanks for bringing this to our attention. This should be fixed on the main branch now. It would be great if you could let us know if the changes resolve your issues.

**Comment by benoitdion** [comment]
@wirthual looks like it will
