### ISSUE TITLE
Different results between sentence-transformers and infinity server

### ISSUE THREAD

**Issue by stikkireddy** [michaelfeil/infinity#384]
### System Info

infinity_emb v2 \
  --model-id Alibaba-NLP/gte-large-en-v1.5 \
  --batch-size 256 \
  --served-model-name default \
  --trust-remote-code \
  --model-warmup \
  --host 0.0.0.0 \
  --port 9989

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

# infinity

```python
client.post(
            url, json={
                "input": [
                             "Your string for the embedding model goes here"
                         ],
}
)
```

# sentence transformers

```python
sentences = ["Your string for the embedding model goes here"]

model = SentenceTransformer('Alibaba-NLP/gte-large-en-v1.5', trust_remote_code=True)
embeddings = model.encode(sentences)
embeddings.tolist()[0]
```

### Expected behavior

I expect the results to be the same

**Comment by stikkireddy** [comment]
it seems its due to normalizing vectors is that fair to say? @michaelfeil?

**Comment by michaelfeil** [comment]
Its by normalizing vectors
