### ISSUE TITLE
Setup Auth Access?

### ISSUE THREAD

**Issue by bendangelo** [michaelfeil/infinity#41]
If I'm wondering if it's possible to add some sort of api key so only authorized users can access the service?

**Comment by bendangelo** [comment]
To give more context it'll be nice if the api token assigned to the instance can hook into the standard openai api. Like so:
client = OpenAI::Client.new(access_token: "access_token_goes_here")

**Comment by bendangelo** [comment]
Yeah I just did exactly that. I used Traefik to add authorization. Thanks

**Comment by michaelfeil** [comment]
If you want to contribute an example with that, would be welcome!

**Comment by bendangelo** [comment]
For now I just used ufw to block outside connections to the port.
```
sudo apt update
sudo apt install ufw
sudo ufw allow 52323
sudo ufw default deny incoming
sudo ufw enable
```

**Comment by michaelfeil** [comment]
Added AUTH.
