### ISSUE TITLE
Maintain: Improve the existing PR / issue templates

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#416]
### System Info

In case soemone has good ideas. 

Could be a simple PR highlighting the contribution should be MIT license, encourage opening an issue.

**Comment by wirthual** [comment]
You created the template in a TEMPLATE subfolder, the document you shared suggests using .github or docs. 

Maybe you want to give it a other try in the .github folder. The Markdown format seems fine, other repos use that as well.

E.g. [here](https://github.com/ggerganov/llama.cpp/blob/master/.github%2Fpull_request_template.md)

**Comment by fadkeabhi** [comment]
@wirthual thanks for the update and the guidance, I will try changes suggested by you and will create a pull request soon.

**Comment by wirthual** [comment]
Hi @fadkeabhi ,

I just verified with #444 that the template was correctly used. Thank you for your contribution.
