### ISSUE TITLE
url prefix is required to start with /

### ISSUE THREAD

**Issue by wirthual** [michaelfeil/infinity#418]
### System Info

Infinity verion: 0.0.63

Output logs:
```
AssertionError: Routed paths must start with '/'
```

Fix:
 use `/v1` as prefix and the server starts as intended.

Possible solutions:
 - Do an input check on the input and update the help text 
 - Prepend / to the input if not provided

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
poetry install -E all
poetry run infinity_emb v2 --url-prefix v1
```

### Expected behavior

Server starts with v1 prefix

**Comment by michaelfeil** [comment]
Good catch
