### ISSUE TITLE
Using infinity service with lite-llm

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [michaelfeil/infinity#427]
### Feature request

It would be good to have a demo of using infinity-svc with `lite-llm`
https://github.com/BerriAI/litellm

I am not able to get reranking service to work.

### Motivation

lite-llm is kind of an interface for all sorts of providers.

**Comment by wirthual** [comment]
Hi @S1LV3RJ1NX ,

@michaelfeil  is right,  Infinitys reranking works great in combination with litellm.

Server
```bash
infinity_emb v2 --url-prefix /v2 --model-id mixedbread-ai/mxbai-rerank-xsmall-v1
```

And for the litellm specific client:
```python
from litellm import rerank
import os

os.environ["COHERE_API_KEY"] = "sk-.."

query = "where is paris?"
documents = ["Paris is in france", "paris is in germany"]

response = rerank(
    model="cohere/local-infinity-model",
    query=query,
    documents=documents,
    top_n=3,
    api_base="http://localhost:7997/v2/rerank",
)
print(response)
````
Result:
```
id='infinity-8c5b9701-e7ef-4719-bf1b-0e28f36139c7' results=[{'relevance_score': 0.6445334553718567, 'index': 0, 'document': 'Paris is in france'}, {'relevance_score': 0.14642126858234406, 'index': 1, 'document': 'paris is in germany'}] meta=None
```

Enjoy :)

**Comment by S1LV3RJ1NX** [comment]
@michaelfeil @wirthual - yes, now it works, as LiteLLM has made the necessary changes. 
Find issue here: https://github.com/BerriAI/litellm/issues/6246

**Comment by michaelfeil** [comment]
@S1LV3RJ1NX Thank you so much for resolving & opening an issue upstream! This was useful!
