### ISSUE TITLE
float16 for image embeddings

### ISSUE THREAD

**Issue by nbroad1881** [michaelfeil/infinity#437]
### System Info

If you use a model like google/siglip-so400m-patch14-384 with default settings, it will give an error that input tensors and weight dtypes are not the same.

This is because the model gets put in float16 but the inputs stay in float32.

You could either modify the `encode_pre` function here: https://github.com/michaelfeil/infinity/blob/62a07c9d91b8bddb999001277563dbbde24844d4/libs/infinity_emb/infinity_emb/transformer/vision/torch_vision.py#L167

Or you could modify `encode_core` here: https://github.com/michaelfeil/infinity/blob/62a07c9d91b8bddb999001277563dbbde24844d4/libs/infinity_emb/infinity_emb/transformer/vision/torch_vision.py#L201-L209

Check if `self.engine.dtype in (Dtype.float16, Dtype.auto)`, and then modify the inputs to be the same type as weights.

### Information

- [X] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run -p 7997:7997 --gpus all michaelf34/infinity:latest --model-id google/siglip-so400m-patch14-384

### Expected behavior

infinity should keep the inputs the same dtype as the model weights.

**Comment by michaelfeil** [comment]
@nbroad1881 Thanks for opening the issue! That is super messed up. 

The image model wants float32/float16/bfloat16. The text model wants int32 (tokens). 
Will ship a fix soon!

**Comment by nbroad1881** [comment]
thanks for the quick fix!
