### ISSUE TITLE
MiniCPM-Embedding support

### ISSUE THREAD

**Issue by gaohongkui** [michaelfeil/infinity#449]
### Model description

Hello, I tested deploying [MiniCPM-Embedding](https://huggingface.co/openbmb/MiniCPM-Embedding) using the latest docker image (0.0.67) of infinity, but found that the inference result is very different from the official example.

* official result
![image](https://github.com/user-attachments/assets/c9686324-56fb-438a-8358-567fbdfcebcd)

* infinity  result
![image](https://github.com/user-attachments/assets/521d93a5-aa76-4e59-afbf-0656f835a615)

* this is a partial screenshot of the startup process
![image](https://github.com/user-attachments/assets/851c110e-f411-4dc3-93af-aeb0721c6619)

* I saw that this model is mentioned in https://github.com/michaelfeil/infinity/issues/354, but there seems to be no discussion result. This model is transformed from a decode-only model, but it is already supported in SentenceTransformer. Does infinity support this kind of model?

### Open source status

- [X] The model implementation is available on transformers
- [X] The model weights are available on huggingface-hub
- [X] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

### Provide useful links for the implementation

https://huggingface.co/openbmb/MiniCPM-Embedding

**Comment by michaelfeil** [comment]
@gaohongkui Please use float32 or bfloat16 as ‘—dtype’ to get the same results. 

Let me know if that helps, and please write a resolution note if it does & close the issue :)

**Comment by gaohongkui** [comment]
`--dtype` not work

I tried to analyze and compare the loading processes of the infinity loading model and MiniCPM-Embedding.
Fix: using `infinity_emb v2 --model-id openbmb/MiniCPM-Embedding --no-bettertransformer --dtype float16`
This can reproduce the results of the official example. 

Specifically, MiniCPM customizes the implementation of [flash-attention-2](https://huggingface.co/openbmb/MiniCPM-Embedding/blob/c0cb2de33fb366e17c30f9d53142ff11bc18e049/modeling_minicpm.py#L474), and its configuration file specifies the default parameter [_attn_implementation = "flash_attention_2"](https://huggingface.co/openbmb/MiniCPM-Embedding/blob/c0cb2de33fb366e17c30f9d53142ff11bc18e049/configuration_minicpm.py#L181). However, when infinity enables `bettertransformer` by default, it will use `eager` to override `attn_implementation`. https://github.com/michaelfeil/infinity/blob/c9a84040be95be2ee5c29bf8679e0501d55328e4/libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py#L54-L64

Additionally, I noticed that there is a judgment for `attn_implementation` in the `to_bettertransformer` method. But this judgment seems not to be triggered when `bettertransformer` is enabled by default. https://github.com/michaelfeil/infinity/blob/c9a84040be95be2ee5c29bf8679e0501d55328e4/libs/infinity_emb/infinity_emb/transformer/acceleration.py#L50-L54

Although we hope that users can be active in turning on `--no-bettertransformer` when using a custom flash attn model, it appears to be tough to readily link this parameter with flash attn. 
Especially when an open - source model doesn't stress that it has altered the implementation of flash attn, this is even more unnoticeable.

Well, how about we think about not actively adding the parameter `model_kwargs["attn_implementation"] = "eager"`? 
When the loaded model has a customized attn_implementation and bettertransformer is turned on, directly show an error to the user and suggest turning off bettertransformer.

**Comment by michaelfeil** [comment]
I understand your confusion and questions on the default. I hope this response brings clarity.

RE: Well, how about we think about not actively adding the parameter model_kwargs["attn_implementation"] = "eager"?
When the loaded model has a customized attn_implementation and bettertransformer is turned on, directly show an error to the user and suggest turning off bettertransformer.

I worked with the Huggingface team on this. If you set bettertransformer + forget eager + transformers > 4.42 you get incorrect results.
On the other hand, bettertransformer allows for 1.5x more throughput and is crucial to run the most popular embedding model such as Bert / Roberta etc. based models.

As there is can be only one default, it better ships with those 1.5x speed improvements (measured via benchmark_embed)

**Comment by gaohongkui** [comment]
ok, understand, thanks~
