### ISSUE TITLE
Support for Model2Vec Embedding models

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [michaelfeil/infinity#451]
### Model description

Do we support Model2Vec embedding models? 

E.g: https://huggingface.co/minishlab/potion-base-8M
https://minishlab.github.io/tokenlearn_blogpost/

### Open source status

- [x] The model implementation is available on transformers
- [x] The model weights are available on huggingface-hub
- [ ] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

**Comment by michaelfeil** [comment]
No. Despite them being uploaded on huggingface, they are not compatible to any of the libraries by hugging face. 

They also used the `config.json` file to package their own glutter https://huggingface.co/minishlab/potion-base-8M/blob/main/config.json. The config.json file is highly standardized.

**Comment by michaelfeil** [comment]
alueError: Unrecognized model in minishlab/potion-base-8M. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, bros, camembert, canine, chameleon, chinese_clip, chinese_clip_vision_model, clap, clip, clip_text_model, clip_vision_model, clipseg, clvp, code_llama, codegen, cohere, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, dac, data2vec-audio, data2vec-text, data2vec-vision, dbrx, deberta, deberta-v2, decision_transformer, deformable_detr, deit, depth_anything, deta, detr, dinat, dinov2, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encodec, encoder-decoder, ernie, ernie_m, esm, falcon, falcon_mamba, fastspeech2_conformer, flaubert, flava, fnet, focalnet, fsmt, funnel, fuyu, gemma, gemma2, git, glpn, gpt-sw3, gpt2, gpt_bigcode, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, granite, granitemoe, graphormer, grounding-dino, groupvit, hiera, hubert, ibert, idefics, idefics2, imagegpt, informer, instructblip, instructblipvideo, jamba, jetmoe, jukebox, kosmos-2, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, llama, llava, llava_next, llava_next_video, llava_onevision, longformer, longt5, luke, lxmert, m2m_100, mamba, mamba2, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, mega, megatron-bert, mgp-str, mimi, mistral, mixtral, mllama, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mobilevitv2, mpnet, mpt, mra, mt5, musicgen, musicgen_melody, mvp, nat, nemotron, nezha, nllb-moe, nougat, nystromformer, olmo, olmoe, omdet-turbo, oneformer, open-llama, openai-gpt, opt, owlv2, owlvit, paligemma, patchtsmixer, patchtst, pegasus, pegasus_x, perceiver, persimmon, phi, phi3, pix2struct, pixtral, plbart, poolformer, pop2piano, prophetnet, pvt, pvt_v2, qdqbert, qwen2, qwen2_audio, qwen2_audio_encoder, qwen2_moe, qwen2_vl, rag, realm, recurrent_gemma, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, rt_detr, rt_detr_resnet, rwkv, sam, seamless_m4t, seamless_m4t_v2, segformer, seggpt, sew, sew-d, siglip, siglip_vision_model, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, stablelm, starcoder2, superpoint, swiftformer, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, timm_backbone, trajectory_transformer, transfo-xl, trocr, tvlt, tvp, udop, umt5, unispeech, unispeech-sat, univnet, upernet, van, video_llava, videomae, vilt, vipllava, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, vitdet, vitmatte, vits, vivit, wav2vec2, wav2vec2-bert, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso, zoedepth

**Comment by michaelfeil** [comment]
Will not be supported, see thread with MinishLab.

**Comment by willavos** [comment]
I just spotted https://huggingface.co/minishlab/potion-base-8M/discussions/3 which suggests there's some work being done to bring their repo inline with using sentence-transformers, as typical with most other models on huggingface.
Their config.json was also updated end of November. Despite these changes I still get a KeyError in infinnity, so, I think I'm going to try and fork their model to make it compatible with infinity. I'll update this comment if I'm successful.

**Comment by stephantul** [comment]
@willavos hello!

Model2Vec maintainer here. This will work when `sentence-transformers` merges [this pr](https://github.com/UKPLab/sentence-transformers/pull/3182) and releases, no need to fork the model.

**Comment by willavos** [comment]
Looks like [that pr](https://github.com/UKPLab/sentence-transformers/pull/3182) among [others](https://github.com/UKPLab/sentence-transformers/commit/db6ce946b55ff24267475a934a22a6061a9bc436) have gone into [sentence-transformers](https://github.com/UKPLab/sentence-transformers). 🥳 Thanks to everyone involved with that.

I guess we just need to wait for the next sentence-transformers release, and for infinity to pick up the new version..?

**Comment by willavos** [comment]
[There's a new model2vec-supporting release of sentence-transformers!](https://github.com/UKPLab/sentence-transformers/releases/tag/v3.4.1)

Please can we bump the sentence-transformers version here? Thank you 😃

**Comment by michaelfeil** [comment]
For the docker container you mean?

**Comment by willavos** [comment]
Yes please, I'm running the `michaelf34/infinity:latest-cpu` image.

**Comment by michaelfeil** [comment]
Please try the michaelf34/infinity:0.0.76rc1-cpu image. If it does not work, report the errors, make an exact reproduction and if possible open a PR with the fix. 

I most likely won't have time to support this until ~End of February/March

**Comment by willavos** [comment]
Not working yet, I think we just lack the latest version of `sentence-transformers` from `huggingface/transformers`.

With running `model-id` as `"minishlab/potion-base-8M"`, I see:
<details>

```

ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 784, in __getitem__
    raise KeyError(key)
KeyError: 'model2vec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/infinity_emb/infinity_server.py", line 88, in lifespan
    app.engine_array = AsyncEngineArray.from_args(engine_args_list)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infinity_emb/engine.py", line 306, in from_args
    return cls(engines=tuple(engines))
                       ^^^^^^^^^^^^^^
  File "/app/infinity_emb/engine.py", line 71, in from_args
    engine = cls(**engine_args.to_dict(), _show_deprecation_warning=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infinity_emb/engine.py", line 56, in __init__
    self._model_replicas, self._min_inference_t, self._max_inference_t = select_model(
                                                                         ^^^^^^^^^^^^^
  File "/app/infinity_emb/inference/select_model.py", line 81, in select_model
    loaded_engine = unloaded_engine.value(engine_args=engine_args_copy)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infinity_emb/transformer/embedder/optimum.py", line 52, in __init__
    self.model = optimize_model(
                 ^^^^^^^^^^^^^^^
  File "/app/infinity_emb/transformer/utils_optimum.py", line 158, in optimize_model
    unoptimized_model = model_class.from_pretrained(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/optimum/onnxruntime/modeling_ort.py", line 737, in from_pretrained
    return super().from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/optimum/modeling_base.py", line 416, in from_pretrained
    config = cls._load_config(
             ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/optimum/modeling_base.py", line 247, in _load_config
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1084, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `model2vec` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or b
ecause your version of Transformers is out of date.

You can update Transformers with the command `pip install --upgrade transformers`. If this does not work, and the checkpoint is very new, then there may not be a release version that supports
 this model yet. In this case, you can get the most up-to-date code by installing Transformers from source with the command `pip install git+https://github.com/huggingface/transformers.git`

```

</details>

I'll have a poke around and see if I can solve this. If I can I'll open a PR. Sorry to use up some of your time here

**Comment by willavos** [comment]
If I attach a shell and `cat requirements.txt` I see:
`sentence-transformers==3.3.1 ; python_version >= "3.9" and python_version < "4"`, which isn't the expected `3.4.1`.

I am unfamiliar with Python tooling, but I think you need to run a `poetry lock` inside `/libs/infinity_emb` ...? After running that command I saw the lock file change, and I appeared to get the expected `sentence-transformers` version, `3.4.1`.

(n.b. `poetry lock` works for poetry version `1.X.X`, but it's opt-in on `2.X.X` with `--regenerate`).

I'm not sure if this needs to be done in any other directories. Hope this helps somehow, and sorry once again for eating up your time.
