### ISSUE TITLE
support for dimensions field like in OpenAI text-embedding-3, thanks

### ISSUE THREAD

**Issue by ericg108** [michaelfeil/infinity#476]
### Feature request

when initializing with SentenceTransformers, we can use the `truncate_dim` argument, like below:
`model = SentenceTransformer("mixedbread-ai/mxbai-embed-large-v1", truncate_dim=dimensions)`

and in calling OpenAI text-embedding-3, we can also pass a `` argument to get variant-length embeddings

`dimensions integer Optional
The number of dimensions the resulting output embeddings should have. Only supported in text-embedding-3 and later models.
`
see also: https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-dimensions

### Motivation

more and more embedding models are supporting Matryoshka embeddings, namely allowing users to get dimensions of varying length, like mxbai-embed-large-v1, jina-embeddings-v3 etc.
this is very useful in scenarios with limited resources. hope it could be supported. Thanks.

### Your contribution

I guess it's not a big modification. I may be able to add this feature when I'm told where to modify. Thanks.

**Comment by ericg108** [comment]
okay. Let me work on this. 
But I'm not familiar with git operations which may take me some time to file a merge request.

**Comment by wirthual** [comment]
@ericg108  with the recent merge to master, you should be able now to truncate the returned embeddings by passing in a `dimension` params just like the openAI api. 

Let me know if that works for you.

**Comment by ericg108** [comment]
@wirthual thank you for your effort. It took me a lot time to learn the codebase and still I didn't find the place to modify the `SentenceTranformer` initialization. 
From your code, I see just slicing the dimension to get the matryoshka embeddings which I didn't expect. Does that mean the underlying implementation is not based on the sentencetransformer so we don't need to modify the `SentenceTranformer` initialization by passing the argument `truncate_dim`? 
Thanks!

**Comment by michaelfeil** [comment]
@ericg108 yes, @ericg108 that's the feature you requested.
It's identical to what "big" inference providers, text-embedding-3 at OpenAI and the original matryoshka paper do. The reason why it works, is that the model was trained to sort the output by importance.

**Comment by ericg108** [comment]
@michaelfeil got it, thanks!

**Comment by wirthual** [comment]
Yes, its the same as passing `truncate_dim` to `sentence_transformers` . You can see the [truncate_embeddings](https://github.com/UKPLab/sentence-transformers/blob/a41aada7d2ce96fe5adea45ddebef97acc3aaeea/sentence_transformers/util.py#L314C5-L314C42) function which is called  [here](https://github.com/UKPLab/sentence-transformers/blob/a41aada7d2ce96fe5adea45ddebef97acc3aaeea/sentence_transformers/SentenceTransformer.py#L627) is simply doing: 
```python
return embeddings[..., :truncate_dim]
```

However if you managed to pass truncate_dims to Sentence Transformers, this might be of interest for issue #482 

Cheers
