### ISSUE TITLE
What are the main differences between using this repo and BentoInfinity?

### ISSUE THREAD

**Issue by noamgershi** [michaelfeil/infinity#495]
Hi
I would like to know if there are differences if I use this repo, or https://github.com/bentoml/BentoInfinity.

**Comment by michaelfeil** [comment]
@noamgershi BentoInfinity is when you have your infrastructure running on BentoML & helps you to get started. 
If you are not running on Bento, this repo is the way to go.

**Comment by noamgershi** [comment]
Thanx!
does BentoML gives me more capabilities? like better performance? (dynamic-batches and concurrent request, etc)

**Comment by michaelfeil** [comment]
No!
