### ISSUE TITLE
Why not support api_key argument?

### ISSUE THREAD

**Issue by BarrySmith** [michaelfeil/infinity#496]
### Feature request

Some embeddings support the api_key argument, this does not. It is very useful when supported

### Motivation

Ease of use

### Your contribution

Unlikely I do not understand the code at all

**Comment by michaelfeil** [comment]
Please read the readme. Search for api key.

```
infinity_emb v2 --api-key "mysecrettoken"
```

**Comment by BarrySmith** [comment]
Thanks. That works,  but it assumes my code would just use your embeddings. If I want to decide at run time between a bunch of embeddings it is painful for each embedding system I need to have special code that use a different way to supply my api_key making my code more complex and more difficult to maintain.

**Comment by michaelfeil** [comment]
Can you hint me to a pointer in the OpenAI API schema or other solutions that do this? (vLLM, oLlama?)
