### ISSUE TITLE
Support Apple Metal

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#55]
I saw @ninehills forked the repo to improve metal support.

I think we could add a metal device here.
https://github.com/michaelfeil/infinity/blob/7556042a2763cff9b3a5795c8350bb2ca6afbcb9/libs/infinity_emb/infinity_emb/primitives.py#L13-L16
@ninehills As I am on WSL, do you want to open a PR from your fork and cotribute your MIT-licenced code? If you `allow edits` I can take it from there.

**Comment by BSVogler** [comment]
I am currently evaluating options on self hosted embeddings servers on Mac OS. Is this all that is needed to make it work on Apple Silicone?

**Comment by ninehills** [comment]
I will open a PR to add the MPS backend as quickly as possible.

Michael Feil ***@***.***>于2024年1月7日 周日19:12写道：

**Comment by ninehills** [comment]
see: https://github.com/michaelfeil/infinity/pull/59

**Comment by michaelfeil** [comment]
Thanks, looks solid. Lets close this issue then.
