### ISSUE TITLE
Support e5-mistral-7b-instruct

### ISSUE THREAD

**Issue by yuhon0528** [michaelfeil/infinity#62]
Will Infinity support [e5-mistral-7b-instruct](https://huggingface.co/intfloat/e5-mistral-7b-instruct)?

Since this model is not support by sentence transformer, I can still use infinity to start the API server for e5-mistral-7b-instruct, but seems the embedding result is not the same as I follow the script in https://huggingface.co/intfloat/e5-mistral-7b-instruct.

**Comment by michaelfeil** [comment]
Hi @yuhon0528, thanks for opening the issue. I know that e5-mistral-instruct is quite good, however It might be still very slow (1-30 embeddings/s), so its lot on top of the things I want to implement next.

Have you tried using `sentence-transformers`? Have you considered contributed a `sentence-transformers` config? I once did that in some of intfloat's repos: https://huggingface.co/intfloat/multilingual-e5-large/discussions/5/files. `sentence-transformers` also just uses HF's `AutoModel` under the hood, my bet is you can load it with the correct config. If so, please contribute it to intfloat's HF repo.

Currently focusing to get e.g. m2 with custom kernels running: https://github.com/michaelfeil/m2-bert - contributions are welcome.

**Comment by michaelfeil** [comment]
See: https://github.com/UKPLab/sentence-transformers/issues/2320

**Comment by yuhon0528** [comment]
Thanks for your advice. I noticed that e5-mistral-instruct is quite slow, and is quite a new way in doing embeddings.

However, I believe it is becoming a trend to finetune small size llm's as embedding models, as you can see in the top rankings in [MTEB Leaderboard](https://huggingface.co/spaces/mteb/leaderboard).

Since we have enough computing resources, we would like to get a more "precise" embedding model for RAG products.

Hugging face and VLLM should also have found the possibility in it, and sentence transformer has already supported this kind of models. See https://huggingface.co/Salesforce/SFR-Embedding-Mistral/discussions/1.

I have tried [SFR-Embedding-Mistral](https://huggingface.co/Salesforce/SFR-Embedding-Mistral/discussions/1) with infinity-emd==0.0.17 and can run success, but seems cannot run in newest release (0.0.25) which shows an error in torch.compile.

Hope to see this new feature recently!

**Comment by michaelfeil** [comment]
Awesome - thanks for your feedback. `export INFINITY_DISABLE_COMPILE=True`?

**Comment by yuhon0528** [comment]
It works! Thanks!

**Comment by michaelfeil** [comment]
Great, thanks for your feedback @yuhon0528. Were you able to verify that the results are as expected?

**Comment by yuhon0528** [comment]
I have tested **SFR-Embedding-Mistral** with the example provided by them, see https://huggingface.co/Salesforce/SFR-Embedding-Mistral#sentence-transformers.

The result should be the same, with only small differences up to decimals.

- My result: [[86.71534476520975, 36.64572982724137], [35.0049448756957, 82.07390591284552]]
- Official: [[86.71537780761719, 36.645721435546875], [35.00497055053711, 82.07388305664062]]

My command to host the model:
`CUDA_VISIBLE_DEVICES=0 INFINITY_DISABLE_OPTIMUM=True INFINITY_DISABLE_HALF=True INFINITY_DISABLE_COMPILE=True infinity_emb --model-name-or-path="/models/SFR-Embedding-Mistral" --port 7999 --batch-size 16 --log-level debug`

The small difference should be due to different GPUs? But I think it is negligible.

**Comment by michaelfeil** [comment]
I think you dont need to disable half / float16 to get a acceptable accuracy in downstream tasks (cosine_sim etc)On 5. Mar 2024, at 17:45, yuhon0528 ***@***.***> wrote:﻿
But seems there is no way to accelerate it now? I must set INFINITY_DISABLE_OPTIMUM=True INFINITY_DISABLE_COMPILE=True to make it runnable and INFINITY_DISABLE_HALF=True to make the difference limited to decimals.

**Comment by yuhon0528** [comment]
I will give it a try. Thanks for your advice!
