### ISSUE TITLE
422 error if /embeddings input is a string

### ISSUE THREAD

**Issue by OlegIvaniv** [michaelfeil/infinity#98]
Hello,

There seems to be a discrepancy between Infinity's `/embeddings` API endpoint and OpenAI. OpenAI supports both `string` and `string[]` as input while Infinity throws 422: Unprocessed Entity for a simple string input. This prevents us from being able to use Infinity endpoint with Langchain's Open AI embeddings as `embedQuery` is sending a string input.

Any chance this could be updated to support both, in line with the OpenAI spec?

Appreciate your work!

Oleg

**Comment by michaelfeil** [comment]
Hey Oleg,

I wrote a infinity integration into Python Langchain.
https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community/embeddings

looking into your syntax, are you using JS/TS?

**Comment by michaelfeil** [comment]
@OlegIvaniv  This is now fixed on the main branch with the latest pydantic upgrades.  #99

**Comment by OlegIvaniv** [comment]
> @OlegIvaniv This is now fixed on the main branch with the latest pydantic upgrades. #99

Works like a charm. Thank you for such a quick response!
